package Calculator.structure;

/*Generated by MPS */

import jetbrains.mps.project.structure.modules.ModuleReference;
import jetbrains.mps.smodel.Language;
import jetbrains.mps.smodel.MPSModuleRepository;

public class Calculator_Language {
  public static ModuleReference MODULE_REFERENCE = ModuleReference.fromString("39883d10-6237-47b8-aa08-556ca7e83f96(Calculator)");

  public static Language get() {
    return (Language) MPSModuleRepository.getInstance().getModule(MODULE_REFERENCE);
  }
}
